### ISSUE TITLE
it has error when export each label cell to each obj file 

### ISSUE THREAD

**Issue by ly000451** [Tai-Hsien/MeshSegNet#7]
see below code to export each label cell to each obj file .
            Vmin=mesh2.cell_attributes['Label'].min()
            Vmax=mesh2.cell_attributes['Label'].max()
            for idx in range(Vmin,Vmax):
                mesh3=Easy_Mesh()
                tooth_idx = np.where(mesh2.cell_attributes['Label']==idx)[0]
                mesh3.cells=mesh2.cells[np.where(mesh2.cell_attributes['Label']==idx)[0]]
                mesh3.update_cell_ids_and_points()
                mesh3.set_cell_labels(mesh2.cell_attributes['Label'][np.where(mesh2.cell_attributes['Label']==idx)[0]])
                mesh3.to_obj(os.path.join(output_path, '{}_{}_toothNumber.obj'.format(i_sample[:-4],idx)))

after execute, script will throw exception
C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\vtk\util\numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
Traceback (most recent call last):
  File "C:\Users\user\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 3215, in <module>
    main()
  File "C:\Users\user\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 3208, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\user\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 2282, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\user\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 2289, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\user\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:\codebase\pythonCodebase\MeshSegNet\MeshSegNet\step6_predict_with_post_processing_pygco.py", line 238, in <module>
    mesh3.set_cell_labels(mesh2.cell_attributes['Label'][np.where(mesh2.cell_attributes['Label']==idx)[0]])
  File "F:\codebase\pythonCodebase\MeshSegNet\MeshSegNet\easy_mesh_vtk.py", line 220, in set_cell_labels
    D = distance_matrix(cell_centers, i_label_cell_centers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\spatial\kdtree.py", line 975, in distance_matrix
    raise ValueError("x contains %d-dimensional vectors but y contains %d-dimensional vectors" % (k, kk))
ValueError: x contains 3-dimensional vectors but y contains 0-dimensional vectors

where is a problem?

**Comment by Tai-Hsien** [comment]
Hello @ly000451 
Do you still have the problem? If not, I will close this issue.

**Comment by ly000451** [comment]
Great. The problem is solved. Good job.
